import MantineProvider from "@/app/MantineProvider";
import SupabaseProvider from "@/app/SupabaseProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MantineProvider>
          <SupabaseProvider>{children}</SupabaseProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
